# Overview

I originally intended to use the TCGA data assembled in indication-level
MultiAssayExperiments from the curatedTCGAData packages as a "feeder" resource
to create the FacileTcgaDataSet. The notes to pointers for those data are below.

Instead I will use the xena data to create the FacileTcgaDataSet for the
following reasons:

1. To create another complementary TCGA resource that is easily accessible
   through R (ie. immune phenoptyes, broader/different subtype information) 
2. To get access to the kallisto transcript level quantitation.
3. Test the FacileBioc package to ensure that the facile API it provides over
   a MultiAssayExperiment works so that the curatedTCGAData MAE objects can
   be easily accessed with the facile API.

## Datasets

We will create a dataset across all indications using the following assays:

### mRNA Abundance

The following assays can be pulled from the curatedTCGAData package:

* `RNASeq2GeneNorm`: fpkm values (sad)
* `RNASeqGene`: v2 fpkm values?
* `miRNASeqGene`: miRNA-seq data

We might consider getting gene and transcript level counts from the recount2
project, though:

https://jhubiostatistics.shinyapps.io/recount/

They used Gencode v25 GFF3 annotations, which we can parse with the utility
funcionts in GemomicsStudyDb

### Copy Number

* `GISTIC_AllByGene`: real valued copy number per gene
* `GISTIC_ThresholdedByGene`: threshold (duplication / deletion / normal)
  gene-level CNV scores

### GenomicVariants

* `Mutation`: mutation status? What does this look like?

### Other

* `RPPAArray`: Reverse Phase Protein Array (NOISY)
* `Methylation`, `Methylation_methyl27`, or `Methylation_methyl450`

Individual indication will be downloaded separately and assembled into one
final FacileTcgaDataSet.

## Data Assembly

Let's follow along with the [curatedTCGAData vignette][curatedvignette]
to figure out how to do this.

[//]: # (References ===========================================================)

[curatedvignette]: http://bioconductor.org/packages/release/data/experiment/vignettes/curatedTCGAData/inst/doc/curatedTCGAData.html
